name: Publish schema

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Create folder
      run: mkdir dist
      
    - name: Bundle schema
      run: python -m tools.bundle_schema --out dist/schema.json
    
    - name: Downgrade schema to draft-07
      run: python -m tools.downgrade_schema_to_draft07 dist/schema.json
    
    - name: Drop $id property
      run: python -m tools.patch_schema dist/schema.json --drop-id
    
    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_branch: gh-pages
